print ("John Paul L. Mangui")
print ("Poras, Boac, Marinduque")
print ("March 20, 2003")
print ("College of Information and Computer Sciences")
print ("Bachelor of Science in Information Technology")
print ("BSI/T 2B")
print("--------------------")
print("Playing Online Games")
print("Singing")
print("Watching Anime")
print("Cycling")
print("Playing Instrument")

